[build]
  publish = "dist"
  command = "pip install -r requirements.txt && mkdir -p dist && cp -r static dist/ && cp templates/index.html dist/index.html"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["uvicorn", "fastapi"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 