[build]
  publish = "dist"
  command = """
    mkdir -p dist &&
    cp -r static dist/ &&
    cp templates/index.html dist/index.html
  """
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]

[functions.api]
  included_files = ["youtube_viewer.py"]

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9" 