[build]
  publish = "dist"
  command = """
    pip install -r requirements.txt &&
    mkdir -p dist &&
    cp -r static dist/ &&
    cp templates/index.html dist/index.html
  """
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  included_files = ["youtube_viewer.py"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 