name: Deploy YouTube Viewer API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install uvicorn
    
    - name: Run FastAPI Server
      run: |
        nohup python -m uvicorn app:app --host 0.0.0.0 --port 8000 &
        echo "FastAPI server started on port 8000"
        
    - name: Keep workflow alive
      run: |
        while true; do
          echo "Server is running..."
          sleep 300
        done 