name: Frontend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'static/**'
  pull_request:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install serve
      run: npm install -g serve
    
    - name: Build static files
      run: |
        mkdir -p dist
        cp -r templates dist/
        cp -r static dist/ || echo "No static files found"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        enable_jekyll: false 