name: Frontend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'static/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create dist structure
      run: |
        mkdir -p dist
        cp -r static dist/
        # Create index.html in root
        cp templates/index.html dist/index.html
        # Update paths in index.html for GitHub Pages
        sed -i 's|href="/static/|href="./static/|g' dist/index.html
        sed -i 's|fetch("/|fetch("./|g' dist/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true 